title: Not a naive blog
description: My Personal Blog
author: Tim Chen
logo: /static/img/avatar.png
github: https://github.com/timchen1997
about: A naive programmer

baseurl: ""
url: "localhost:4000"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
